repos:
  - repo: https://github.com/psf/black
    rev: 26.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        language: node
        entry: react-app/node_modules/.bin/eslint --ext .js,.jsx react-app/src
        types: [file]
        files: \.[jt]sx?$
        pass_filenames: false
        additional_dependencies: []

      - id: prettier
        name: prettier
        language: node
        entry: react-app/node_modules/.bin/prettier --write
        types_or: [javascript, jsx, ts, tsx, css, json, html]
        additional_dependencies: []
