# Build and Deploy Python Code App on Azure
# Manually triggered from build-azure.yml
# https://aka.ms/yaml

trigger: none
pr: none
appendCommitMessageToRunName: true

pool:
  name: Default
  demands:
  - Agent.Name -equals vmlsha1

resources:
- repo: self

variables:
  - group: arc_iasc

  - name: appName
    ${{ if eq( variables['Build.SourceBranchName'], 'release' ) }}:
      value: 'duuksawharciasc01'
    ${{ if ne( variables['Build.SourceBranchName'], 'release' ) }}:
      value: 'duuksawharciascdevel01'
    
  - name: azureSubscription
    value: 'svc-con-awh-01'
  - name: resourceGroupName
    value: 'du-uks-awh-arc-iasc01'

  - name: containerRegistryName
    value: 'https://index.docker.io/v1'
  - name: dockerfile
    value: '$(Build.SourcesDirectory)/Dockerfile'
  - name: dockerRegistryServiceConnection
    value: 'DurhamARCDockerHub'
  - name: imageRepository
    value: 'durhamarc/iasc'

stages:
  - stage: Release
    displayName: Release
    jobs:
      - job: Release
        displayName: Release
        steps:
          - script: |
              commitHash=${sourceVersion:0:8}
              echo ${commitHash}
              echo "##vso[task.setvariable variable=commitHash]$commitHash"
            env: { sourceVersion: $(Build.SourceVersion) }
            displayName: Git Hash 8-digit

          # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4
          - task: AzureRmWebAppDeployment@4
            inputs:
              appType: 'webAppContainer'
              deployToSlotOrASE: true
              ResourceGroupName: '$(resourceGroupName)'
              azureSubscription: '$(azureSubscription)'
              WebAppName: '$(appName)'
              DockerNamespace: $(DOCKER_REGISTRY_SERVER_URL)
              DockerRepository: $(imageRepository)
              # commitHash defined in above script.
              DockerImageTag: $(commitHash)
              AppSettings: >-
                -ALLOWED_HOSTS "$(ALLOWED_HOSTS)"
                -SITE_URL "$(SITE_URL)"
                -CSRF_TRUSTED_ORIGINS "$(CSRF_TRUSTED_ORIGINS)"
                -DB_HOST "$(DB_HOST)"
                -DB_PORT "$(DB_PORT)"
                -DB_NAME "$(DB_NAME)"
                -DB_PASS "$(DB_PASS)"
                -DB_USER "$(DB_USER)"
                -DB_SSL_ENABLED "$(DB_SSL_ENABLED)"

          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: $(azureSubscription)
              Action: 'Restart Azure App Service'
              WebAppName: $(appName)
