# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- pipelines

pool:
  name: Default
  demands:
  - Agent.Name -equals vmlsha1

resources:
- repo: self


variables:
  - name: appName
    value: 'duuksawharciasc01' # Update this value.
  - name: webAppResourceGroupName
    value: 'du-uks-awh-arc-iasc01' # Update this value.
  - name: runtimeStack
    value: 'PYTHON|3.8' # Update this value.
  - name: allowedHosts
    value: 'iasc.awh.durham.ac.uk'

stages:
  - stage: Build
    displayName: Build and zip content
    jobs:
      - job: Build
        displayName: Build
        steps:
          - checkout: self
          - script: |
              sudo apt-get -y install zip
              echo  '$(System.DefaultWorkingDirectory)'
            displayName: Run script

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
              replaceExistingArchive: true
            displayName: "Archive Files"

          - publish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
            artifact: $(appName)
            displayName: "Upload Artifact"

  - stage: Release
    displayName: Release
    jobs:
      - job: Release
        displayName: Release
        steps:
          - script: |
              echo  '$(System.DefaultWorkingDirectory)'
            displayName: Run script

          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: $(appName)
              targetPath: '$(System.DefaultWorkingDirectory)'

          # https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-rm-web-app-deployment-v4
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'svc-con-awh-01'
              appType: 'webAppLinux'
              WebAppName: '$(appName)'
              deployToSlotOrASE: true
              ResourceGroupName: '$(webAppResourceGroupName)'
              SlotName: 'production'
              packageForLinux: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
              RuntimeStack: '$(runtimeStack)'
              StartupCommand: 'gunicorn --bind=0.0.0.0:8000 iasc.wsgi'
              ScriptType: 'Inline Script'
              AppSettings: >-
                -SCM_DO_BUILD_DURING_DEPLOYMENT "true"
                -ENABLE_ORYX_BUILD "true"
                -ALLOWED_HOSTS "$(allowedHosts)"
              InlineScript: |
                export WORKDIR=$(pwd)
                echo "\$WORKDIR is $WORKDIR"
                echo "\$PYTHONPATH is $PYTHONPATH"
                echo "\$PATH is $PATH"
                echo "python3.8 is $(which python3.8)"
                echo "Creating virtual environment:"
                python3.8 -m venv antenv
                chmod +x ./antenv/bin/activate
                echo "Activating virtual environment:"
                . ./antenv/bin/activate
                echo "python is $(which python)"
                echo "Install requirements..."
                python -m pip install -r requirements.txt
                python -m pip install django
