# Generated by Django 4.1 on 2023-05-13 00:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_link",
                    models.CharField(
                        help_text="Per-participant / survey unique voting link",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Scientific Discipline, e.g. 'Physicist'",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Institution Name, e.g. Durham University",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(help_text="Host Country", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("active", models.BooleanField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("LI", "Likert")], default="LI", max_length=2
                    ),
                ),
                (
                    "expiry",
                    models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
                ),
                ("participants", models.IntegerField(default=0)),
                ("voted", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.JSONField()),
                (
                    "discipline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.discipline",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.institution",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.survey",
                    ),
                ),
                (
                    "unique_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.activelink",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "email",
                    models.CharField(
                        help_text="Participant Email",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="First & Family/Surname", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Participant Title",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iasc.discipline",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iasc.institution",
                    ),
                ),
            ],
            options={
                "ordering": ["-email"],
            },
        ),
        migrations.AddField(
            model_name="activelink",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iasc.participant"
            ),
        ),
        migrations.AddField(
            model_name="activelink",
            name="survey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="iasc.survey",
            ),
        ),
        migrations.AddIndex(
            model_name="activelink",
            index=models.Index(
                fields=["unique_link"], name="iasc_active_unique__073cc0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activelink",
            constraint=models.UniqueConstraint(
                fields=("participant", "survey"),
                name="unique_migration_host_combination",
            ),
        ),
    ]
