# Generated by Django 4.1 on 2023-04-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_link",
                    models.CharField(
                        help_text="Per-participant / survey unique voting link",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Scientific Discipline, e.g. 'Physicist'",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Institution Name, e.g. Durham University",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(help_text="Host Country", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("active", models.BooleanField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("LI", "Likert")], default="LI", max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Results",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vote", models.JSONField()),
                (
                    "discipline",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.discipline",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.institution",
                    ),
                ),
                (
                    "unique_link",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iasc.activelinks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="First & Family/Surname", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Participant Title",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "email",
                    models.CharField(help_text="Participant Email", max_length=255),
                ),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iasc.discipline",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="iasc.institution",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activelinks",
            name="participant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="iasc.participant"
            ),
        ),
        migrations.AddField(
            model_name="activelinks",
            name="survey_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="iasc.survey",
            ),
        ),
        migrations.AddConstraint(
            model_name="activelinks",
            constraint=models.UniqueConstraint(
                fields=("participant_id", "survey_id"),
                name="unique_migration_host_combination",
            ),
        ),
    ]
