# Generated by Django 4.1 on 2023-05-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iasc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participant",
            name="email",
            field=models.EmailField(
                help_text="Participant Email",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
