# Generated by Django 4.1 on 2023-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iasc", "0003_rename_activelinks_activelink_rename_results_result_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activelink",
            index=models.Index(
                fields=["unique_link"], name="iasc_active_unique__073cc0_idx"
            ),
        ),
    ]
