# Generated by Django 4.1 on 2023-05-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iasc", "0004_remove_result_unique_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="country",
            field=models.CharField(
                blank=True, help_text="Host Country", max_length=255
            ),
        ),
    ]
