# Generated by Django 6.0.3 on 2026-03-24 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iasc", "0005_alter_institution_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="survey",
            name="expiry",
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
    ]
