# Generated by Django 6.0.3 on 2026-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iasc", "0006_alter_survey_expiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="questions",
            field=models.JSONField(
                blank=True,
                help_text="List of statement strings for multi-question templates (e.g. L3C)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="survey",
            name="kind",
            field=models.CharField(
                choices=[("LI", "Likert"), ("L3C", "Likert (3 + Expertise)")],
                default="LI",
                max_length=3,
            ),
        ),
    ]
