# Generated by Django 6.0.3 on 2026-03-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iasc", "0008_alter_survey_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="hide_title",
            field=models.BooleanField(
                default=True,
                help_text="If True, the survey title is not shown to participants",
            ),
        ),
    ]
