# Generated by Django 6.0.3 on 2026-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iasc", "0009_add_hide_title_to_survey"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=32, unique=True)),
                (
                    "slots",
                    models.JSONField(
                        help_text="Ordered list of question slots: [{id, type, placeholder}]"
                    ),
                ),
                ("is_builtin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
