name: CI

# Run this workflow after Unit Tests succeed
on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-pipeline-name: DurhamARC.IASCPolls
            azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_URL }}
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
