name: Release to Azure

# Run this workflow after Unit Tests succeed
on:
workflow_run:
  workflows: ["Unit Tests"]
  types:
    - completed

jobs:
  build:
    name: Call Azure Pipeline
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-pipeline-name: DurhamARC.IASCPolls
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_URL }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
