# A Github Actions configuration for building Docker images for ManyFEWS
name: Build Docker Images

on:
  push:
    branches:
      - release

env:
  DOCKERHUB_REPO: ${{ secrets.AZURE_ACR_REGISTRY }}/arc/iasc

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.sha.outputs.short_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.AZURE_ACR_REGISTRY }}
          username: ${{ secrets.AZURE_ACR_USER }}
          password: ${{ secrets.AZURE_ACR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      # https://stackoverflow.com/questions/58033366/how-to-get-the-current-branch-within-github-actions
      - name: Add SHORT_SHA and BRANCH to env
        id: sha
        run: |
          echo "SHORT_SHA=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV \
          && echo "short_sha=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT \
          && echo "BRANCH=release" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          target: iasc
          tags: >
            ${{ env.DOCKERHUB_REPO }}:latest , 
            ${{ env.DOCKERHUB_REPO }}:${{ env.SHORT_SHA }} ,
            ${{ env.DOCKERHUB_REPO }}:${{ env.BRANCH }}
          cache-from: type=registry,ref=${{ env.DOCKERHUB_REPO }}:cache
          cache-to: type=registry,ref=${{ env.DOCKERHUB_REPO }}:cache,mode=max

  release-prod:
    name: Release to Azure Pipelines Production
    needs: docker
    runs-on: ubuntu-latest

    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-pipeline-name: DurhamARC.IASCPolls
          azure-devops-project-url: ${{ secrets.AZURE_DEVOPS_URL }}
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
          azure-pipeline-variables: '{"commitHash": "${{ needs.docker.outputs.short_sha }}"}'
