name: Unit Tests
on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  test:
    name: Set up and test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: arc_iasc
          POSTGRES_PASSWORD: arc_iasc
          POSTGRES_DB: arc_iasc
        ports:
          - 5432:5432
        # The Postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        name: Cache Miniconda environment
        with:
          path: /usr/share/miniconda3/envs/anaconda-client-env
          key: conda-${{ runner.os }}--${{ runner.arch }}--${{ steps.get-date.outputs.today }}-${{ hashFiles('conf/iasc.base.yml') }}-${{ env.CACHE_NUMBER }}
        env:
          # Increase this to manually invalidate the cache
          CACHE_NUMBER: 0 +
        id: cache

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: anaconda-client-env
          environment-file: conf/iasc.base.yml
          python-version: 3.9
          channels: conda-forge
          # IMPORTANT! This needs to be set for caching to work properly:
          use-only-tar-bz2: true

      - name: Run Django tests
        env:
          ALLOWED_HOSTS: localhost,127.0.0.1
        run: python manage.py test

